name: E-Commerce Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/ECOM
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ["5.0.11"]
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          ENV_REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          ENV_EMAIL_USER: ${{ secrets.EMAIL_USER }}
          ENV_EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          ENV_MONGO_URL: ${{ secrets.MONGO_URL }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: npm install
      - run: npm test
